### ISSUE TITLE
[Feature Request] Is there any plan to make an Anki add-on?

### ISSUE THREAD

**Issue by Cycatz** [kaiiiz/python-ankicc#1]
I was wondering if this tool can be made as an Anki add-on, providing more features like partial conversion, etc.

**Comment by kaiiiz** [comment]
You're right. The ultimate goal of such a feature should work directly inside Anki.

Since the software stack of the Anki plugin is built on top of python, I think it's possible to port this project to an Anki plugin, providing a native user experience with more features. However, I have no experience developing an Anki plugin and currently have only a little time can work on it. The development of this project may be extremely slow (at least in the near future). But overall, thanks for the suggestions.

**Comment by Cycatz** [comment]
Thanks for the fast reply! 

Recently I started to use anki as my daily life tool, so I also wish this feature can be implemented in the future. If I have time, I can help survey how to make an anki addon.

**Comment by kaiiiz** [comment]
Hi, I recently conducted a survey on the development of Anki add-ons and have successfully created a new one. Please refer to [AnkiCC](https://github.com/kaiiiz/AnkiCC) for more details. Although it currently looks quite "basic", I believe it offers a more user-friendly experience compared to this Python package. ;)

**Comment by kaiiiz** [comment]
BTW, feel free to open issues in the new repo. I'll close this issue later.
